version: '3'
services:

  nicochcgi:
    image: ghcr.io/kurema/nicochcgi/nicochcgi:latest
    container_name: nicochcgi-server
    restart: always
    ports: 
      # Port for http
      # HTTP用ポート
      # DO NOT CHANGE ":80"
      - 50001:80
    volumes:
      - ./config:/etc/nicochcgi
      # Video cache directory
      # 動画キャッシュの保存場所
      # DO NOT CHANGE ":/media/niconico"
      - ./videos:/media/niconico
    
# docker-compose up -d
# docker-compose stop
# docker-compose rm
# docker-compose down
# docker-compose down --rmi all
