version: '3'
services:

  nicochcgi:
    image: ghcr.io/kurema/nicochcgi/nicochcgi:latest
    container_name: nicochcgi-server
    ports: 
      - 50001:80
    volumes:
      - ./config:/etc/nicochcgi
      - ./config/.netrc:/var/www/.netrc
      - ./videos:/media/niconico
    
